// <auto-generated />
using System;
using BistroQ.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BistroQ.Infrastructure.Migrations
{
    [DbContext(typeof(BistroQContext))]
    [Migration("20241228045041_FinalMigration")]
    partial class FinalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BistroQ.Core.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TableId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "638f17c2-5405-4e6f-b43e-40afd8788672",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGZSlN5nxCd8sK83PjOpgvl4b40ZeJCx1xW+aR/fFWV8pLR8dDRoNOaDxJZavTNNvA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6b578dd3-df4c-4127-8ae0-d0d54ec5416b",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "71ce686c-a356-4ca1-863a-27b9f11658ac",
                            Email = "kitchen@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "KITCHEN@GMAIL.COM",
                            NormalizedUserName = "KITCHEN",
                            PasswordHash = "AQAAAAIAAYagAAAAEH7E/cVnQRZiDy5tnqC1Qp+AuesCl/kSPnAvRDxcPqmVUelhyW5fHdxT5Iff/li09g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cba74f2b-f465-4987-8e7b-fc9cf4571626",
                            TwoFactorEnabled = false,
                            UserName = "kitchen"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f155d7e4-cb7d-4ec6-bfc8-f336ce952db3",
                            Email = "cashier@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CASHIER@GMAIL.COM",
                            NormalizedUserName = "CASHIER",
                            PasswordHash = "AQAAAAIAAYagAAAAEHosHTvM+aREydkhTv8ZHnOaem+eNxNCem/sJjvpKfXUCIKaVT93R3pL/Pvy4MPtxQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "369f9d0a-f50f-4806-abf8-abd865ee62ff",
                            TwoFactorEnabled = false,
                            UserName = "cashier"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b8e54401-4023-4823-b19a-636b511e524a",
                            Email = "client1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT1@GMAIL.COM",
                            NormalizedUserName = "CLIENT1",
                            PasswordHash = "AQAAAAIAAYagAAAAEPzVPUtP69AXQSV0Lq8H/+8UsCRgzQRQ/tFQ7Vy+4Jv7cWeDjEIes0zijScHu1VgeQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ab226b0-5366-4c2d-81f1-368cdc8009d1",
                            TableId = 1,
                            TwoFactorEnabled = false,
                            UserName = "client1"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3117e11d-bd97-400a-8fe4-15737bcf517b",
                            Email = "client2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT2@GMAIL.COM",
                            NormalizedUserName = "CLIENT2",
                            PasswordHash = "AQAAAAIAAYagAAAAEMnb7r1EsvN1br0ZiA+gG81SBMX1csRU9aW43/022pajQu5oMNHBOSDdJPwZWhT+Aw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d2d19548-5b96-4f4c-a199-df8dc92e837a",
                            TableId = 2,
                            TwoFactorEnabled = false,
                            UserName = "client2"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "77c908ab-3549-44ad-bef3-85ad016bbf72",
                            Email = "client3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT3@GMAIL.COM",
                            NormalizedUserName = "CLIENT3",
                            PasswordHash = "AQAAAAIAAYagAAAAEFe381muNntSkenCVNR2E9bSz74TXG9dHQZ/y3iMJiUhM5gKnITT9D+KgKBHuU4xcA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "309cf38f-f927-4c38-a9b1-cfdbc82246e3",
                            TableId = 3,
                            TwoFactorEnabled = false,
                            UserName = "client3"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4e80b6b9-5e3b-43d8-9a78-05c3e0c3528b",
                            Email = "client4@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT4@GMAIL.COM",
                            NormalizedUserName = "CLIENT4",
                            PasswordHash = "AQAAAAIAAYagAAAAEML/mAvTvi+pgYMz+rYJM5ZSTiLfLVVZ4P3z+L711CkMNo94SJNtnAywh1f0DweLDg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d4243a69-483a-4d7b-a7a1-438f09df6477",
                            TableId = 4,
                            TwoFactorEnabled = false,
                            UserName = "client4"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3bce3609-abf2-4382-83b0-eb056e4daebd",
                            Email = "client5@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT5@GMAIL.COM",
                            NormalizedUserName = "CLIENT5",
                            PasswordHash = "AQAAAAIAAYagAAAAEPjNx3uW4kzEN/kiWF3GohGOLnvtSwWUAPb132fnfwR0UgrnzxYfRgc7R6ENNGicNg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "968981bd-6489-44f1-9ed4-26f526dfae29",
                            TableId = 5,
                            TwoFactorEnabled = false,
                            UserName = "client5"
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cd187681-3902-4f9b-bc89-ea380c4e59a2",
                            Email = "client6@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT6@GMAIL.COM",
                            NormalizedUserName = "CLIENT6",
                            PasswordHash = "AQAAAAIAAYagAAAAEMAGtO9+9YxCgw6OJAnC4n9CXu+yBQCroHfXpiipSyxjqN2a3CqAfj+AAphMFOhMRg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6374c13a-8a44-4135-9cfd-a7c6744f9404",
                            TableId = 6,
                            TwoFactorEnabled = false,
                            UserName = "client6"
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a72f432a-f664-4325-8345-0431082fd361",
                            Email = "client7@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT7@GMAIL.COM",
                            NormalizedUserName = "CLIENT7",
                            PasswordHash = "AQAAAAIAAYagAAAAEA8fv8QkVOtD3q7Cp6miivxMbdK120K87FE6wyRNAlT9Jsn4TOi7ecoyVC+D8cIAtA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cab89db9-5c8e-46ec-950e-3a7a5c19b230",
                            TableId = 7,
                            TwoFactorEnabled = false,
                            UserName = "client7"
                        },
                        new
                        {
                            Id = "11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6cb84dc3-5896-4e1e-a7c6-2316ad75e105",
                            Email = "client8@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT8@GMAIL.COM",
                            NormalizedUserName = "CLIENT8",
                            PasswordHash = "AQAAAAIAAYagAAAAENUrvD6hCU4iZYFVkxUBYsgC5pXGoeSS3FbHInQA/Ssv6aNDR0eK4gUQxjhGKRx17Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "778d11e5-2ef5-4e98-bd18-4b01ef2cfad5",
                            TableId = 8,
                            TwoFactorEnabled = false,
                            UserName = "client8"
                        },
                        new
                        {
                            Id = "12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e61cf8b8-2063-4009-81de-6c7d651e62ab",
                            Email = "client9@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT9@GMAIL.COM",
                            NormalizedUserName = "CLIENT9",
                            PasswordHash = "AQAAAAIAAYagAAAAEItNfrzhNnX3r+NUNXLkxIbRD6TpT2pttqN3uDH88Pkm3w2wh5g5lijNF9JLWEib1w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "da332dab-c7ba-49c8-b3d9-e959f488141c",
                            TableId = 9,
                            TwoFactorEnabled = false,
                            UserName = "client9"
                        },
                        new
                        {
                            Id = "13",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "451d639a-1d86-4fc9-b049-515cb4a63934",
                            Email = "client10@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT10@GMAIL.COM",
                            NormalizedUserName = "CLIENT10",
                            PasswordHash = "AQAAAAIAAYagAAAAEJUJAPgHj7qUh/mlRIKiotnWz9X7y5ayxaITGUv75W0c5vCMKqMT2mR3RZub9qMeHQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "17930c4b-5873-4665-bc04-325b7dc329cc",
                            TableId = 10,
                            TwoFactorEnabled = false,
                            UserName = "client10"
                        });
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PRIMARY");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Dry"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Broth-based"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Spicy"
                        });
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Image", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ImageId")
                        .HasName("PRIMARY");

                    b.ToTable("Image", (string)null);

                    b.HasData(
                        new
                        {
                            ImageId = new Guid("00000000-0000-0000-0000-000000000001"),
                            ContentType = "image/jpeg",
                            Name = "bun-bo-hue.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("00000000-0000-0000-0000-000000000002"),
                            ContentType = "image/jpeg",
                            Name = "pho.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("00000000-0000-0000-0000-000000000003"),
                            ContentType = "image/jpeg",
                            Name = "banh-mi.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("00000000-0000-0000-0000-000000000004"),
                            ContentType = "image/jpeg",
                            Name = "banh-xeo.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("00000000-0000-0000-0000-000000000005"),
                            ContentType = "image/jpeg",
                            Name = "banh-canh.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("00000000-0000-0000-0000-000000000006"),
                            ContentType = "image/jpeg",
                            Name = "banh-cuon.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("00000000-0000-0000-0000-000000000007"),
                            ContentType = "image/jpeg",
                            Name = "com-chien.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("00000000-0000-0000-0000-000000000008"),
                            ContentType = "image/jpeg",
                            Name = "bun-rieu.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("00000000-0000-0000-0000-000000000009"),
                            ContentType = "image/jpeg",
                            Name = "bun-thit-nuong.jpg"
                        },
                        new
                        {
                            ImageId = new Guid("00000000-0000-0000-0000-000000000010"),
                            ContentType = "image/jpeg",
                            Name = "mi-xao.jpg"
                        });
                });

            modelBuilder.Entity("BistroQ.Core.Entities.NutritionFact", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<double?>("Calories")
                        .HasColumnType("double");

                    b.Property<double?>("Carbohydrates")
                        .HasColumnType("double");

                    b.Property<double?>("Fat")
                        .HasColumnType("double");

                    b.Property<double?>("Fiber")
                        .HasColumnType("double");

                    b.Property<double?>("Protein")
                        .HasColumnType("double");

                    b.HasKey("ProductId")
                        .HasName("PRIMARY");

                    b.ToTable("NutritionFact", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Calories = 479.0,
                            Carbohydrates = 50.0,
                            Fat = 15.0,
                            Fiber = 3.0,
                            Protein = 25.0
                        },
                        new
                        {
                            ProductId = 2,
                            Calories = 431.0,
                            Carbohydrates = 45.0,
                            Fat = 8.0,
                            Fiber = 2.0,
                            Protein = 25.0
                        },
                        new
                        {
                            ProductId = 3,
                            Calories = 461.0,
                            Carbohydrates = 55.0,
                            Fat = 15.0,
                            Fiber = 3.0,
                            Protein = 20.0
                        },
                        new
                        {
                            ProductId = 4,
                            Calories = 517.0,
                            Carbohydrates = 41.600000000000001,
                            Fat = 16.699999999999999,
                            Fiber = 2.2999999999999998,
                            Protein = 8.4000000000000004
                        },
                        new
                        {
                            ProductId = 5,
                            Calories = 379.0,
                            Carbohydrates = 45.0,
                            Fat = 12.0,
                            Fiber = 2.0,
                            Protein = 18.0
                        },
                        new
                        {
                            ProductId = 6,
                            Calories = 590.0,
                            Carbohydrates = 45.0,
                            Fat = 8.0,
                            Fiber = 2.0,
                            Protein = 5.0
                        },
                        new
                        {
                            ProductId = 7,
                            Calories = 530.0,
                            Carbohydrates = 55.0,
                            Fat = 20.0,
                            Fiber = 3.0,
                            Protein = 15.0
                        },
                        new
                        {
                            ProductId = 8,
                            Calories = 482.0,
                            Carbohydrates = 45.0,
                            Fat = 10.0,
                            Fiber = 3.0,
                            Protein = 20.0
                        },
                        new
                        {
                            ProductId = 9,
                            Calories = 451.0,
                            Carbohydrates = 45.0,
                            Fat = 15.0,
                            Fiber = 3.0,
                            Protein = 18.0
                        },
                        new
                        {
                            ProductId = 10,
                            Calories = 650.0,
                            Carbohydrates = 65.0,
                            Fat = 18.0,
                            Fiber = 4.0,
                            Protein = 22.0
                        });
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.HasKey("OrderId")
                        .HasName("PRIMARY");

                    b.HasIndex("TableId")
                        .IsUnique();

                    b.HasIndex(new[] { "TableId" }, "TableId");

                    b.ToTable("Order", (string)null);

                    b.HasData(
                        new
                        {
                            OrderId = "1",
                            PeopleCount = 5,
                            StartTime = new DateTime(2024, 12, 28, 11, 50, 40, 725, DateTimeKind.Local).AddTicks(5355),
                            Status = 0,
                            TableId = 1,
                            TotalAmount = 490000m
                        },
                        new
                        {
                            OrderId = "2",
                            PeopleCount = 2,
                            StartTime = new DateTime(2024, 12, 28, 11, 50, 40, 725, DateTimeKind.Local).AddTicks(5514),
                            Status = 0,
                            TableId = 6,
                            TotalAmount = 265000m
                        },
                        new
                        {
                            OrderId = "3",
                            PeopleCount = 4,
                            StartTime = new DateTime(2024, 12, 28, 11, 50, 40, 725, DateTimeKind.Local).AddTicks(5550),
                            Status = 0,
                            TableId = 2,
                            TotalAmount = 115000m
                        },
                        new
                        {
                            OrderId = "4",
                            EndTime = new DateTime(2024, 10, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            PeopleCount = 0,
                            StartTime = new DateTime(2024, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalAmount = 30000m
                        },
                        new
                        {
                            OrderId = "5",
                            EndTime = new DateTime(2024, 10, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            PeopleCount = 0,
                            StartTime = new DateTime(2024, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalAmount = 50000m
                        },
                        new
                        {
                            OrderId = "6",
                            EndTime = new DateTime(2024, 10, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            PeopleCount = 0,
                            StartTime = new DateTime(2024, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TotalAmount = 45000m
                        });
                });

            modelBuilder.Entity("BistroQ.Core.Entities.OrderItem", b =>
                {
                    b.Property<string>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValueSql("(UUID())");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("PriceAtPurchase")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("OrderItemId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "OrderId" }, "OrderId");

                    b.HasIndex(new[] { "ProductId" }, "ProductId");

                    b.ToTable("OrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            OrderItemId = "101",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "1",
                            PriceAtPurchase = 50000m,
                            ProductId = 1,
                            Quantity = 2,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "102",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "1",
                            PriceAtPurchase = 50000m,
                            ProductId = 2,
                            Quantity = 1,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "103",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "1",
                            PriceAtPurchase = 25000m,
                            ProductId = 3,
                            Quantity = 1,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "104",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "1",
                            PriceAtPurchase = 35000m,
                            ProductId = 4,
                            Quantity = 2,
                            Status = 0,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "105",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "1",
                            PriceAtPurchase = 40000m,
                            ProductId = 5,
                            Quantity = 1,
                            Status = 2,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "106",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "1",
                            PriceAtPurchase = 30000m,
                            ProductId = 6,
                            Quantity = 3,
                            Status = 0,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "107",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "1",
                            PriceAtPurchase = 25000m,
                            ProductId = 7,
                            Quantity = 1,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "108",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "1",
                            PriceAtPurchase = 45000m,
                            ProductId = 8,
                            Quantity = 2,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "201",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "2",
                            PriceAtPurchase = 25000m,
                            ProductId = 3,
                            Quantity = 3,
                            Status = 2,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "202",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "2",
                            PriceAtPurchase = 35000m,
                            ProductId = 4,
                            Quantity = 2,
                            Status = 2,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "203",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "2",
                            PriceAtPurchase = 40000m,
                            ProductId = 5,
                            Quantity = 1,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "204",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "2",
                            PriceAtPurchase = 30000m,
                            ProductId = 6,
                            Quantity = 1,
                            Status = 0,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "205",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "2",
                            PriceAtPurchase = 25000m,
                            ProductId = 7,
                            Quantity = 2,
                            Status = 0,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "301",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "3",
                            PriceAtPurchase = 35000m,
                            ProductId = 4,
                            Quantity = 1,
                            Status = 1,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "302",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "3",
                            PriceAtPurchase = 40000m,
                            ProductId = 5,
                            Quantity = 2,
                            Status = 2,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "401",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "4",
                            PriceAtPurchase = 30000m,
                            ProductId = 6,
                            Quantity = 1,
                            Status = 2,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "501",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "5",
                            PriceAtPurchase = 25000m,
                            ProductId = 7,
                            Quantity = 2,
                            Status = 2,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderItemId = "601",
                            CreatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderId = "6",
                            PriceAtPurchase = 45000m,
                            ProductId = 8,
                            Quantity = 1,
                            Status = 2,
                            UpdatedAt = new DateTime(2023, 10, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountPrice")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.Property<string>("Unit")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProductId")
                        .HasName("PRIMARY");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex(new[] { "CategoryId" }, "CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            DiscountPrice = 0m,
                            ImageId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Bun Bo Hue",
                            Price = 50000m,
                            Unit = "Bowl"
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            DiscountPrice = 0m,
                            ImageId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Name = "Pho",
                            Price = 50000m,
                            Unit = "Bowl"
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            DiscountPrice = 0m,
                            ImageId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Name = "Banh Mi",
                            Price = 25000m,
                            Unit = "Piece"
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            DiscountPrice = 0m,
                            ImageId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Name = "Banh Xeo",
                            Price = 35000m,
                            Unit = "Piece"
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            DiscountPrice = 0m,
                            ImageId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Name = "Banh Canh",
                            Price = 40000m,
                            Unit = "Bowl"
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            DiscountPrice = 0m,
                            ImageId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Name = "Banh Cuon",
                            Price = 30000m,
                            Unit = "Plate"
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            DiscountPrice = 0m,
                            ImageId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Name = "Com Chien",
                            Price = 25000m,
                            Unit = "Plate"
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            DiscountPrice = 0m,
                            ImageId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Name = "Bun Rieu",
                            Price = 45000m,
                            Unit = "Bowl"
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            DiscountPrice = 0m,
                            ImageId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Name = "Bun Thit Nuong",
                            Price = 40000m,
                            Unit = "Bowl"
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            DiscountPrice = 0m,
                            ImageId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Name = "Mi Xao",
                            Price = 45000m,
                            Unit = "Plate"
                        });
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("SeatsCount")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("TableId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ZoneId" }, "ZoneId");

                    b.ToTable("Table", (string)null);

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Number = 1,
                            SeatsCount = 4,
                            ZoneId = 1
                        },
                        new
                        {
                            TableId = 2,
                            Number = 2,
                            SeatsCount = 4,
                            ZoneId = 1
                        },
                        new
                        {
                            TableId = 3,
                            Number = 3,
                            SeatsCount = 8,
                            ZoneId = 1
                        },
                        new
                        {
                            TableId = 4,
                            Number = 4,
                            SeatsCount = 6,
                            ZoneId = 1
                        },
                        new
                        {
                            TableId = 5,
                            Number = 1,
                            SeatsCount = 2,
                            ZoneId = 2
                        },
                        new
                        {
                            TableId = 6,
                            Number = 2,
                            SeatsCount = 2,
                            ZoneId = 2
                        },
                        new
                        {
                            TableId = 7,
                            Number = 3,
                            SeatsCount = 3,
                            ZoneId = 2
                        },
                        new
                        {
                            TableId = 8,
                            Number = 4,
                            SeatsCount = 3,
                            ZoneId = 2
                        },
                        new
                        {
                            TableId = 9,
                            Number = 1,
                            SeatsCount = 3,
                            ZoneId = 3
                        },
                        new
                        {
                            TableId = 10,
                            Number = 2,
                            SeatsCount = 2,
                            ZoneId = 3
                        },
                        new
                        {
                            TableId = 11,
                            Number = 5,
                            SeatsCount = 4,
                            ZoneId = 1
                        },
                        new
                        {
                            TableId = 12,
                            Number = 3,
                            SeatsCount = 5,
                            ZoneId = 3
                        });
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Zone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ZoneId")
                        .HasName("PRIMARY");

                    b.ToTable("Zone", (string)null);

                    b.HasData(
                        new
                        {
                            ZoneId = 1,
                            Name = "Inside"
                        },
                        new
                        {
                            ZoneId = 2,
                            Name = "Backyard"
                        },
                        new
                        {
                            ZoneId = 3,
                            Name = "Outside"
                        },
                        new
                        {
                            ZoneId = 4,
                            Name = "VIP"
                        },
                        new
                        {
                            ZoneId = 5,
                            Name = "Front"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Kitchen",
                            NormalizedName = "KITCHEN"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Cashier",
                            NormalizedName = "CASHIER"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "5",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "6",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "7",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "8",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "9",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "10",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "11",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "12",
                            RoleId = "4"
                        },
                        new
                        {
                            UserId = "13",
                            RoleId = "4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("BistroQ.Core.Entities.AppUser", b =>
                {
                    b.HasOne("BistroQ.Core.Entities.Table", "Table")
                        .WithOne("User")
                        .HasForeignKey("BistroQ.Core.Entities.AppUser", "TableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Table_ibfk_2");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("BistroQ.Core.Entities.NutritionFact", b =>
                {
                    b.HasOne("BistroQ.Core.Entities.Product", "Product")
                        .WithOne("NutritionFact")
                        .HasForeignKey("BistroQ.Core.Entities.NutritionFact", "ProductId")
                        .IsRequired()
                        .HasConstraintName("NutritionFact_ibfk_1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Order", b =>
                {
                    b.HasOne("BistroQ.Core.Entities.Table", "Table")
                        .WithOne("Order")
                        .HasForeignKey("BistroQ.Core.Entities.Order", "TableId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Order_ibfk_1");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("BistroQ.Core.Entities.OrderItem", b =>
                {
                    b.HasOne("BistroQ.Core.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("OrderItem_ibfk_1");

                    b.HasOne("BistroQ.Core.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("OrderItem_ibfk_2");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Product", b =>
                {
                    b.HasOne("BistroQ.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Product_ibfk_1");

                    b.HasOne("BistroQ.Core.Entities.Image", "Image")
                        .WithOne("Product")
                        .HasForeignKey("BistroQ.Core.Entities.Product", "ImageId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Product_ibfk_2");

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Table", b =>
                {
                    b.HasOne("BistroQ.Core.Entities.Zone", "Zone")
                        .WithMany("Tables")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("Table_ibfk_1");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BistroQ.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BistroQ.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BistroQ.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BistroQ.Core.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Image", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Product", b =>
                {
                    b.Navigation("NutritionFact");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Table", b =>
                {
                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BistroQ.Core.Entities.Zone", b =>
                {
                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
